object Libs {
    const val APP_COMPAT = "androidx.appcompat:appcompat"
    const val CONSTRAINT_LAYOUT = "androidx.constraintlayout:constraintlayout"
    const val CORE_KTX = "androidx.core:core-ktx"
    const val COROUTINES_ANDROID = "org.jetbrains.kotlinx:kotlinx-coroutines-android"
    const val GLIDE = "com.github.bumptech.glide:glide"
    const val GLIDE_COMPILER = "com.github.bumptech.glide:compiler"
    const val HILT_ANDROID = "com.google.dagger:hilt-android"
    const val HILT_COMPILER = "com.google.dagger:hilt-compiler"
    const val LIFECYCLE_RUNTIME_KTX = "androidx.lifecycle:lifecycle-runtime-ktx"
    const val MATERIAL = "com.google.android.material:material"
    const val NAVIGATION_FRAGMENT_KTX = "androidx.navigation:navigation-fragment-ktx"
    const val NAVIGATION_UI_KTX = "androidx.navigation:navigation-ui-ktx"
    const val PAGING = "androidx.paging:paging-runtime"
    const val RECYCLER_VIEW = "androidx.recyclerview:recyclerview"
    const val ROOM = "androidx.room:room-runtime"
    const val ROOM_COMPILER = "androidx.room:room-compiler"
    const val ROOM_KTX = "androidx.room:room-ktx"
    const val ROOM_PAGING = "androidx.room:room-paging"

    const val RETROFIT = "com.squareup.retrofit2:retrofit"
    const val CONVERTER_SCALARS = "com.squareup.retrofit2:converter-scalars"
    const val CONVERTER_MOSHI = "com.squareup.retrofit2:converter-moshi"
    const val MOSHI_KOTLIN = "com.squareup.moshi:moshi-kotlin"
    const val MOSHI_KOTLIN_CODEGEN = "com.squareup.moshi:moshi-kotlin-codegen"
    const val LOGGING_INTERCEPTOR = "com.squareup.okhttp3:logging-interceptor"

    const val IGDB_API_JVM = "com.github.husnjak:IGDB-API-JVM"
}
